### ISSUE TITLE
HTTP error occurred: {"error": "Failed to parse Connect Session Auth Token"}

### ISSUE THREAD

**Issue by AlexanderENTH** [stanislavulrych/tempo-api-python-client#21]
Hi everyone,

I have been trying to use this package to update specific values of pre-existing elements I created under /my-work/week.
So I started simple by just displaying every element available. I created both a jira api-token and a Tempo API-token as well as creating the tempo instance like this:
```
tempo = client_v4.Tempo(
        base_url=#URL TO ACCESS TEMPO IN BROWSER#
        auth_token=#JIRA-TOKEN OR TEMPO-TOKEN#,
    )
worklogs = tempo.get_user_schedule(
        dateFrom="2023-06-12",
        dateTo="2023-06-13"
    )

    print(worklogs)

    for i in worklogs:
        print(i)
```

no matter what I tried the following message is displayed:
```
HTTP error occurred: {"error": "Failed to parse Connect Session Auth Token"}
403 Client Error: Forbidden for url: #URL TO ACCESS TEMPO IN BROWSER#/user-schedule?from=2023-06-12&to=2023-06-13
```

Am I missing an important detail here?

**Comment by stanislavulrych** [comment]
Hi @AlexanderENTH,

if you are using JIRA Cloud with Tempo API, do not provide any `base_url` for Tempo client. The code below works fine for me. Please try it.

Stanislav

```
tempo = client_v4.Tempo(
        auth_token=#JIRA-TOKEN OR TEMPO-TOKEN#,
    )
worklogs = tempo.get_user_schedule(
        dateFrom="2023-06-12",
        dateTo="2023-06-13"
    )

    print(worklogs)

    for i in worklogs:
        print(i)
```
