### ISSUE TITLE
RestAPIClient._response_handler raises unnecessarily on 204 (no content) response

### ISSUE THREAD

**Issue by Darkdragon84** [stanislavulrych/tempo-api-python-client#22]
`RestAPIClient._response_handler` calls `response.json()` which raises a `json.decoder.JSONDecodeError` on 204 responses, since their content is empty. Can we catch this case separately and check for empty content?

**Comment by Darkdragon84** [comment]
will you make a new release with the fix?

**Comment by stanislavulrych** [comment]
@Darkdragon84 done.

**Comment by Darkdragon84** [comment]
sweet, thanks!
